In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

# Load your data

In [2]:
X_train = np.loadtxt("/content/drive/MyDrive/input.csv", delimiter=",")
y_train = np.loadtxt("/content/drive/MyDrive/labels.csv", delimiter=",")

X_test = np.loadtxt("/content/drive/MyDrive/input_test.csv", delimiter=",")
y_test = np.loadtxt("/content/drive/MyDrive/labels_test.csv", delimiter=",")

# Prepearing the data

In [3]:
X_train = X_train.reshape(len(X_train),100,100,3) / 255.0
y_train= y_train.reshape(len(y_train),1)

X_test= X_test.reshape(len(X_test),100,100,3) / 255.0
y_test= y_test.reshape(len(y_test),1)

# Load pre-trained model without top layers

In [4]:
import tensorflow as tf
base_model = tf.keras.applications.xception.Xception(weights="imagenet", include_top=False, input_shape=(100,100,3))

# from tensorflow.keras.applications import ResNet50
# base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(100,100,3))

# from tensorflow.keras.applications import VGG16
# base_model = VGG16(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import DenseNet121
# base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import InceptionV3
# base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import MobileNetV2
# base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import EfficientNetB0
# base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(100, 100, 3))


# Add custom classification layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
output_layer = Dense(1, activation='sigmoid')(x)
# output_layer = tf.keras.layers.Dense(n_classes, activation="softmax")(avg)

# Create the new model
model = Model(inputs = base_model.input, outputs = output_layer)


83683744/83683744 [==============================] - 0s 0us/step


# Lets freeze all the layers

In [5]:
for layer in base_model.layers:
  layer.trainable = False

In [6]:
# Compile the model

# optimizer = tf.keras.optimizers.Adam(learning_rate=0.2)
# optimizer = tf.keras.optimizers.SGD(learning_rate=0.2, momentum=0.9)

# model.compile(loss="sparse_categorical_crossentropy", optimizer=optimizer, metrics=["accuracy"])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

Epoch 1/10
57/57 [==============================] - 54s 901ms/step - loss: 0.3317 - accuracy: 0.8422 - val_loss: 0.2696 - val_accuracy: 0.8700
Epoch 2/10
57/57 [==============================] - 56s 979ms/step - loss: 0.1794 - accuracy: 0.9317 - val_loss: 0.2697 - val_accuracy: 0.8650
Epoch 3/10
57/57 [==============================] - 51s 895ms/step - loss: 0.1514 - accuracy: 0.9417 - val_loss: 0.1573 - val_accuracy: 0.9350
Epoch 4/10
57/57 [==============================] - 52s 921ms/step - loss: 0.1085 - accuracy: 0.9606 - val_loss: 0.3672 - val_accuracy: 0.8550
Epoch 5/10
57/57 [==============================] - 51s 895ms/step - loss: 0.0672 - accuracy: 0.9828 - val_loss: 0.3232 - val_accuracy: 0.8700
Epoch 6/10
57/57 [==============================] - 65s 1s/step - loss: 0.0438 - accuracy: 0.9917 - val_loss: 0.3483 - val_accuracy: 0.8550
Epoch 7/10
57/57 [==============================] - 60s 1s/step - loss: 0.0302 - accuracy: 0.9961 - val_loss: 0.2786 - val_accuracy: 0.9100
Epoch

In [7]:
# Making predictions using our model

import numpy as np

y_pred = model.predict(X_test)
y_pred_classes = np.where(y_pred >= 0.5, 1, 0)

13/13 [==============================] - 11s 769ms/step


In [8]:
#Evaluate the model

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# For accuracy measurement
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)

# For confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(confusion_matrix)

# For classification report
classification_report = classification_report(y_test, y_pred_classes)
print("Classification Report:")
print(classification_report)

Accuracy: 0.895
Confusion Matrix:
[[182  18]
 [ 24 176]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.91      0.90       200
         1.0       0.91      0.88      0.89       200

    accuracy                           0.90       400
   macro avg       0.90      0.90      0.89       400
weighted avg       0.90      0.90      0.89       400



#Lets make all the layers of the base model trainable.

In [4]:
# import tensorflow as tf
# base_model = tf.keras.applications.xception.Xception(weights="imagenet", include_top=False, input_shape=(100,100,3))

from tensorflow.keras.applications import ResNet50
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(100,100,3))

# from tensorflow.keras.applications import VGG16
# base_model = VGG16(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import DenseNet121
# base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import InceptionV3
# base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import MobileNetV2
# base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import EfficientNetB0
# base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(100, 100, 3))


# Add custom classification layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
output_layer = Dense(1, activation='sigmoid')(x)
# output_layer = tf.keras.layers.Dense(n_classes, activation="softmax")(avg)

# Create the new model
model_2 = Model(inputs = base_model.input, outputs = output_layer)


94765736/94765736 [==============================] - 3s 0us/step


In [5]:
for layer in base_model.layers:
  layer.trainable = True

In [6]:
# Compile the model
optimizer = tf.keras.optimizers.SGD(learning_rate=0.02, momentum=0.9)
model_2.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

# Train the model
model_2.fit(X_train, y_train, epochs=10, batch_size=16, validation_split=0.1)

Epoch 1/10
113/113 [==============================] - 39s 86ms/step - loss: 0.6630 - accuracy: 0.6378 - val_loss: 0.4685 - val_accuracy: 1.0000
Epoch 2/10
113/113 [==============================] - 8s 73ms/step - loss: 0.5697 - accuracy: 0.7083 - val_loss: 0.3882 - val_accuracy: 1.0000
Epoch 3/10
113/113 [==============================] - 7s 63ms/step - loss: 0.4935 - accuracy: 0.7522 - val_loss: 0.3974 - val_accuracy: 1.0000
Epoch 4/10
113/113 [==============================] - 7s 65ms/step - loss: 0.4209 - accuracy: 0.8111 - val_loss: 0.4135 - val_accuracy: 1.0000
Epoch 5/10
113/113 [==============================] - 7s 64ms/step - loss: 0.3938 - accuracy: 0.8300 - val_loss: 0.3966 - val_accuracy: 1.0000
Epoch 6/10
113/113 [==============================] - 7s 66ms/step - loss: 0.3845 - accuracy: 0.8394 - val_loss: 0.3748 - val_accuracy: 0.9950
Epoch 7/10
113/113 [==============================] - 7s 63ms/step - loss: 0.2519 - accuracy: 0.9050 - val_loss: 0.1515 - val_accuracy: 1.000

In [7]:
# Make predictions using our model
import numpy as np

y_pred = model_2.predict(X_test)
y_pred_classes = np.where(y_pred >= 0.5, 1, 0)

13/13 [==============================] - 2s 25ms/step


In [8]:
#Evaluating the model

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# For accuracy measurement
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)

# For confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(confusion_matrix)

# For classification report
classification_report = classification_report(y_test, y_pred_classes)
print("Classification Report:")
print(classification_report)

Accuracy: 0.8325
Confusion Matrix:
[[158  42]
 [ 25 175]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.86      0.79      0.83       200
         1.0       0.81      0.88      0.84       200

    accuracy                           0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400



#Lets make roughly the last 10% the layers of the base model trainable.

In [16]:
# import tensorflow as tf
# base_model = tf.keras.applications.xception.Xception(weights="imagenet", include_top=False, input_shape=(100,100,3))

from tensorflow.keras.applications import ResNet50
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(100,100,3))

# from tensorflow.keras.applications import VGG16
# base_model = VGG16(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import DenseNet121
# base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import InceptionV3
# base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import MobileNetV2
# base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(100, 100, 3))

# from tensorflow.keras.applications import EfficientNetB0
# base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(100, 100, 3))


# Add custom classification layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
output_layer = Dense(1, activation='sigmoid')(x)
# output_layer = tf.keras.layers.Dense(n_classes, activation="softmax")(avg)

# Create the new model
model_3 = Model(inputs = base_model.input, outputs = output_layer)


In [21]:
# Divide the layers into two groups
num_layers = len(base_model.layers)
split_index = round(num_layers // 1.1)
for layer in base_model.layers[:split_index]:
    layer.trainable = False
for layer in base_model.layers[split_index:]:
    layer.trainable = True


In [22]:
# Compile the model
optimizer = tf.keras.optimizers.SGD(learning_rate=0.02, momentum=0.9)
model_3.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

# Train the model
model_3.fit(X_train, y_train, epochs=10, batch_size=16, validation_split=0.1)

Epoch 1/10
113/113 [==============================] - 9s 36ms/step - loss: 0.5217 - accuracy: 0.7422 - val_loss: 0.7044 - val_accuracy: 0.7300
Epoch 2/10
113/113 [==============================] - 3s 27ms/step - loss: 0.5045 - accuracy: 0.7606 - val_loss: 0.4140 - val_accuracy: 0.7450
Epoch 3/10
113/113 [==============================] - 3s 30ms/step - loss: 0.5071 - accuracy: 0.7600 - val_loss: 0.2788 - val_accuracy: 0.8800
Epoch 4/10
113/113 [==============================] - 3s 31ms/step - loss: 0.4859 - accuracy: 0.7744 - val_loss: 0.2895 - val_accuracy: 0.9050
Epoch 5/10
113/113 [==============================] - 3s 27ms/step - loss: 0.5008 - accuracy: 0.7606 - val_loss: 0.2877 - val_accuracy: 0.8200
Epoch 6/10
113/113 [==============================] - 3s 26ms/step - loss: 0.4814 - accuracy: 0.7672 - val_loss: 0.2342 - val_accuracy: 0.8750
Epoch 7/10
113/113 [==============================] - 3s 27ms/step - loss: 0.4946 - accuracy: 0.7667 - val_loss: 0.8582 - val_accuracy: 0.5950

In [23]:
# Make predictions using our model
import numpy as np

y_pred = model_3.predict(X_test)
y_pred_classes = np.where(y_pred >= 0.5, 1, 0)

13/13 [==============================] - 2s 34ms/step


In [24]:
# Evaluating the model

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# For accuracy measurement
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)

# For confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(confusion_matrix)

# For classification report
classification_report = classification_report(y_test, y_pred_classes)
print("Classification Report:")
print(classification_report)

Accuracy: 0.715
Confusion Matrix:
[[152  48]
 [ 66 134]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.70      0.76      0.73       200
         1.0       0.74      0.67      0.70       200

    accuracy                           0.71       400
   macro avg       0.72      0.72      0.71       400
weighted avg       0.72      0.71      0.71       400

